Import('env')

sourceFiles = [
    'ServerHandler.cpp',
    'SocketServer.cpp',
    'TcpSocketServerImpl.cpp',
    'UdpSocketServerImpl.cpp',
]

env.Library(target = 'socketServer', source = sourceFiles)
